name: Collaborative Workflow

on:
    push:
        branches:
            - main
# the workflow will run whenever there is a push event on the main branch

jobs:
    update_html_and_readme:
        runs-on: ubuntu-latest
        steps:
            # Step 1: Checkout the repository
            - name: Checkout Repository
              uses: actions/checkout@v3
            
            - name: Verify actor is a teammate
              id: teammate_check
              run: |
                case "${{ github.actor }}" in
                  alice|bob|charlie) echo "ok=true" >> "$GITHUB_OUTPUT" ;;
                  *)                  echo "ok=false" >> "$GITHUB_OUTPUT" ;;
                esac
            - name: Stop if not a teammate
              if: steps.teammate_check.outputs.ok == 'false'
              run: |
                echo "Actor ${{ github.actor }} not in allowed list; skipping."
                exit 0

            - name: Append update note into index.html
            # Mirrors the sed pattern in the brief; inserts just before </body>
              run: |
                if ! grep -q "</body>" index.html; then
                    echo "ERROR: index.html is missing </body>." >&2
                    exit 1
                fi
                sed -i '/<\/body>/i <p>Updated by '"${{ github.actor }}"' on '"$(date)"'</p>' index.html

            - name: Append log entry to README.md
              run: |
                short_sha="$(git rev-parse --short HEAD)"
                printf '### Updated by %s on %s [Commit: %s]\n' \
                        "${{ github.actor }}" \
                        "$(date '+%Y-%m-%d %H:%M:%S')" \
                        "$short_sha" >> README.md

            - name: Commit and push changes
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                git config --global user.name  "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"

                git add -A
                git commit -m "Workflow: Updated HTML and README for ${{ github.actor }}" || echo "No changes to commit"

                # Ensure HTTPS remote w/ token
                git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}"
                git push origin HEAD:main